/** Country reference list (Arabic labels) used by the residency dropdowns. */
export type Country = { code: string; ar: string };

export const COUNTRIES: Country[] = [
  { code: "SA", ar: "السعودية" },
  { code: "EG", ar: "مصر" },
  { code: "SY", ar: "سوريا" },
  { code: "YE", ar: "اليمن" },
  { code: "JO", ar: "الأردن" },
  { code: "PS", ar: "فلسطين" },
  { code: "SD", ar: "السودان" },
  { code: "LB", ar: "لبنان" },
  { code: "IQ", ar: "العراق" },
  { code: "KW", ar: "الكويت" },
  { code: "BH", ar: "البحرين" },
  { code: "QA", ar: "قطر" },
  { code: "AE", ar: "الإمارات" },
  { code: "OM", ar: "عُمان" },
  { code: "MA", ar: "المغرب" },
  { code: "DZ", ar: "الجزائر" },
  { code: "TN", ar: "تونس" },
  { code: "LY", ar: "ليبيا" },
  { code: "MR", ar: "موريتانيا" },
  { code: "SO", ar: "الصومال" },
  { code: "DJ", ar: "جيبوتي" },
  { code: "KM", ar: "جزر القمر" },
  { code: "PK", ar: "باكستان" },
  { code: "IN", ar: "الهند" },
  { code: "BD", ar: "بنغلاديش" },
  { code: "LK", ar: "سريلانكا" },
  { code: "NP", ar: "نيبال" },
  { code: "PH", ar: "الفلبين" },
  { code: "ID", ar: "إندونيسيا" },
  { code: "MY", ar: "ماليزيا" },
  { code: "AF", ar: "أفغانستان" },
  { code: "IR", ar: "إيران" },
  { code: "TR", ar: "تركيا" },
  { code: "AZ", ar: "أذربيجان" },
  { code: "UZ", ar: "أوزبكستان" },
  { code: "KZ", ar: "كازاخستان" },
  { code: "NG", ar: "نيجيريا" },
  { code: "GH", ar: "غانا" },
  { code: "KE", ar: "كينيا" },
  { code: "ET", ar: "إثيوبيا" },
  { code: "ER", ar: "إريتريا" },
  { code: "TD", ar: "تشاد" },
  { code: "ML", ar: "مالي" },
  { code: "NE", ar: "النيجر" },
  { code: "SN", ar: "السنغال" },
  { code: "CM", ar: "الكاميرون" },
  { code: "ZA", ar: "جنوب أفريقيا" },
  { code: "GB", ar: "بريطانيا" },
  { code: "US", ar: "الولايات المتحدة" },
  { code: "CA", ar: "كندا" },
  { code: "FR", ar: "فرنسا" },
  { code: "DE", ar: "ألمانيا" },
  { code: "IT", ar: "إيطاليا" },
  { code: "ES", ar: "إسبانيا" },
  { code: "NL", ar: "هولندا" },
  { code: "SE", ar: "السويد" },
  { code: "RU", ar: "روسيا" },
  { code: "CN", ar: "الصين" },
  { code: "JP", ar: "اليابان" },
  { code: "KR", ar: "كوريا الجنوبية" },
  { code: "AU", ar: "أستراليا" },
  { code: "BR", ar: "البرازيل" },
  { code: "OTHER", ar: "دولة أخرى" },
];

export const countryLabel = (code: string) =>
  COUNTRIES.find((c) => c.code === code)?.ar ?? code;