/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StagesRouteImport } from './routes/stages'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SchoolLifeRouteImport } from './routes/school-life'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrimaryRouteImport } from './routes/primary'
import { Route as NewsRouteImport } from './routes/news'
import { Route as KindergartenRouteImport } from './routes/kindergarten'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdmissionsIndexRouteImport } from './routes/admissions.index'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedMyApplicationsRouteImport } from './routes/_authenticated/my-applications'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAmsIndexRouteImport } from './routes/_authenticated/ams/index'
import { Route as AuthenticatedTrackApplicationIdRouteImport } from './routes/_authenticated/track.$applicationId'
import { Route as AuthenticatedApplyNewRouteImport } from './routes/_authenticated/apply.new'
import { Route as AuthenticatedApplyApplicationIdRouteImport } from './routes/_authenticated/apply.$applicationId'
import { Route as AuthenticatedAmsWaitingListRouteImport } from './routes/_authenticated/ams/waiting-list'
import { Route as AuthenticatedAmsSeatsRouteImport } from './routes/_authenticated/ams/seats'
import { Route as AuthenticatedAmsReportsRouteImport } from './routes/_authenticated/ams/reports'
import { Route as AuthenticatedAmsQueueRouteImport } from './routes/_authenticated/ams/queue'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin/users'
import { Route as AuthenticatedAdminAuditRouteImport } from './routes/_authenticated/admin/audit'
import { Route as AdmissionsStageSlugIndexRouteImport } from './routes/admissions.stage.$slug.index'
import { Route as AdmissionsStageSlugClassroomsRouteImport } from './routes/admissions.stage.$slug.classrooms'
import { Route as AuthenticatedAmsApplicationsApplicationIdRouteImport } from './routes/_authenticated/ams/applications.$applicationId'
import { Route as AdmissionsStageSlugClassroomClassroomSlugRouteImport } from './routes/admissions.stage.$slug.classroom.$classroomSlug'

const StagesRoute = StagesRouteImport.update({
  id: '/stages',
  path: '/stages',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SchoolLifeRoute = SchoolLifeRouteImport.update({
  id: '/school-life',
  path: '/school-life',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrimaryRoute = PrimaryRouteImport.update({
  id: '/primary',
  path: '/primary',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const KindergartenRoute = KindergartenRouteImport.update({
  id: '/kindergarten',
  path: '/kindergarten',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmissionsIndexRoute = AdmissionsIndexRouteImport.update({
  id: '/admissions/',
  path: '/admissions/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMyApplicationsRoute =
  AuthenticatedMyApplicationsRouteImport.update({
    id: '/my-applications',
    path: '/my-applications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAmsIndexRoute = AuthenticatedAmsIndexRouteImport.update({
  id: '/ams/',
  path: '/ams/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTrackApplicationIdRoute =
  AuthenticatedTrackApplicationIdRouteImport.update({
    id: '/track/$applicationId',
    path: '/track/$applicationId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedApplyNewRoute = AuthenticatedApplyNewRouteImport.update({
  id: '/apply/new',
  path: '/apply/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedApplyApplicationIdRoute =
  AuthenticatedApplyApplicationIdRouteImport.update({
    id: '/apply/$applicationId',
    path: '/apply/$applicationId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAmsWaitingListRoute =
  AuthenticatedAmsWaitingListRouteImport.update({
    id: '/ams/waiting-list',
    path: '/ams/waiting-list',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAmsSeatsRoute = AuthenticatedAmsSeatsRouteImport.update({
  id: '/ams/seats',
  path: '/ams/seats',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAmsReportsRoute = AuthenticatedAmsReportsRouteImport.update({
  id: '/ams/reports',
  path: '/ams/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAmsQueueRoute = AuthenticatedAmsQueueRouteImport.update({
  id: '/ams/queue',
  path: '/ams/queue',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminAuditRoute = AuthenticatedAdminAuditRouteImport.update({
  id: '/admin/audit',
  path: '/admin/audit',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AdmissionsStageSlugIndexRoute =
  AdmissionsStageSlugIndexRouteImport.update({
    id: '/admissions/stage/$slug/',
    path: '/admissions/stage/$slug/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdmissionsStageSlugClassroomsRoute =
  AdmissionsStageSlugClassroomsRouteImport.update({
    id: '/admissions/stage/$slug/classrooms',
    path: '/admissions/stage/$slug/classrooms',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAmsApplicationsApplicationIdRoute =
  AuthenticatedAmsApplicationsApplicationIdRouteImport.update({
    id: '/ams/applications/$applicationId',
    path: '/ams/applications/$applicationId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AdmissionsStageSlugClassroomClassroomSlugRoute =
  AdmissionsStageSlugClassroomClassroomSlugRouteImport.update({
    id: '/admissions/stage/$slug/classroom/$classroomSlug',
    path: '/admissions/stage/$slug/classroom/$classroomSlug',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/gallery': typeof GalleryRoute
  '/kindergarten': typeof KindergartenRoute
  '/news': typeof NewsRoute
  '/primary': typeof PrimaryRoute
  '/reset-password': typeof ResetPasswordRoute
  '/school-life': typeof SchoolLifeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stages': typeof StagesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/my-applications': typeof AuthenticatedMyApplicationsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/admissions/': typeof AdmissionsIndexRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/ams/queue': typeof AuthenticatedAmsQueueRoute
  '/ams/reports': typeof AuthenticatedAmsReportsRoute
  '/ams/seats': typeof AuthenticatedAmsSeatsRoute
  '/ams/waiting-list': typeof AuthenticatedAmsWaitingListRoute
  '/apply/$applicationId': typeof AuthenticatedApplyApplicationIdRoute
  '/apply/new': typeof AuthenticatedApplyNewRoute
  '/track/$applicationId': typeof AuthenticatedTrackApplicationIdRoute
  '/ams/': typeof AuthenticatedAmsIndexRoute
  '/ams/applications/$applicationId': typeof AuthenticatedAmsApplicationsApplicationIdRoute
  '/admissions/stage/$slug/classrooms': typeof AdmissionsStageSlugClassroomsRoute
  '/admissions/stage/$slug/': typeof AdmissionsStageSlugIndexRoute
  '/admissions/stage/$slug/classroom/$classroomSlug': typeof AdmissionsStageSlugClassroomClassroomSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/gallery': typeof GalleryRoute
  '/kindergarten': typeof KindergartenRoute
  '/news': typeof NewsRoute
  '/primary': typeof PrimaryRoute
  '/reset-password': typeof ResetPasswordRoute
  '/school-life': typeof SchoolLifeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stages': typeof StagesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/my-applications': typeof AuthenticatedMyApplicationsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/admissions': typeof AdmissionsIndexRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/ams/queue': typeof AuthenticatedAmsQueueRoute
  '/ams/reports': typeof AuthenticatedAmsReportsRoute
  '/ams/seats': typeof AuthenticatedAmsSeatsRoute
  '/ams/waiting-list': typeof AuthenticatedAmsWaitingListRoute
  '/apply/$applicationId': typeof AuthenticatedApplyApplicationIdRoute
  '/apply/new': typeof AuthenticatedApplyNewRoute
  '/track/$applicationId': typeof AuthenticatedTrackApplicationIdRoute
  '/ams': typeof AuthenticatedAmsIndexRoute
  '/ams/applications/$applicationId': typeof AuthenticatedAmsApplicationsApplicationIdRoute
  '/admissions/stage/$slug/classrooms': typeof AdmissionsStageSlugClassroomsRoute
  '/admissions/stage/$slug': typeof AdmissionsStageSlugIndexRoute
  '/admissions/stage/$slug/classroom/$classroomSlug': typeof AdmissionsStageSlugClassroomClassroomSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/gallery': typeof GalleryRoute
  '/kindergarten': typeof KindergartenRoute
  '/news': typeof NewsRoute
  '/primary': typeof PrimaryRoute
  '/reset-password': typeof ResetPasswordRoute
  '/school-life': typeof SchoolLifeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stages': typeof StagesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/my-applications': typeof AuthenticatedMyApplicationsRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/admissions/': typeof AdmissionsIndexRoute
  '/_authenticated/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/ams/queue': typeof AuthenticatedAmsQueueRoute
  '/_authenticated/ams/reports': typeof AuthenticatedAmsReportsRoute
  '/_authenticated/ams/seats': typeof AuthenticatedAmsSeatsRoute
  '/_authenticated/ams/waiting-list': typeof AuthenticatedAmsWaitingListRoute
  '/_authenticated/apply/$applicationId': typeof AuthenticatedApplyApplicationIdRoute
  '/_authenticated/apply/new': typeof AuthenticatedApplyNewRoute
  '/_authenticated/track/$applicationId': typeof AuthenticatedTrackApplicationIdRoute
  '/_authenticated/ams/': typeof AuthenticatedAmsIndexRoute
  '/_authenticated/ams/applications/$applicationId': typeof AuthenticatedAmsApplicationsApplicationIdRoute
  '/admissions/stage/$slug/classrooms': typeof AdmissionsStageSlugClassroomsRoute
  '/admissions/stage/$slug/': typeof AdmissionsStageSlugIndexRoute
  '/admissions/stage/$slug/classroom/$classroomSlug': typeof AdmissionsStageSlugClassroomClassroomSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/faq'
    | '/forgot-password'
    | '/gallery'
    | '/kindergarten'
    | '/news'
    | '/primary'
    | '/reset-password'
    | '/school-life'
    | '/sitemap.xml'
    | '/stages'
    | '/dashboard'
    | '/my-applications'
    | '/profile'
    | '/admissions/'
    | '/admin/audit'
    | '/admin/users'
    | '/ams/queue'
    | '/ams/reports'
    | '/ams/seats'
    | '/ams/waiting-list'
    | '/apply/$applicationId'
    | '/apply/new'
    | '/track/$applicationId'
    | '/ams/'
    | '/ams/applications/$applicationId'
    | '/admissions/stage/$slug/classrooms'
    | '/admissions/stage/$slug/'
    | '/admissions/stage/$slug/classroom/$classroomSlug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/faq'
    | '/forgot-password'
    | '/gallery'
    | '/kindergarten'
    | '/news'
    | '/primary'
    | '/reset-password'
    | '/school-life'
    | '/sitemap.xml'
    | '/stages'
    | '/dashboard'
    | '/my-applications'
    | '/profile'
    | '/admissions'
    | '/admin/audit'
    | '/admin/users'
    | '/ams/queue'
    | '/ams/reports'
    | '/ams/seats'
    | '/ams/waiting-list'
    | '/apply/$applicationId'
    | '/apply/new'
    | '/track/$applicationId'
    | '/ams'
    | '/ams/applications/$applicationId'
    | '/admissions/stage/$slug/classrooms'
    | '/admissions/stage/$slug'
    | '/admissions/stage/$slug/classroom/$classroomSlug'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/contact'
    | '/faq'
    | '/forgot-password'
    | '/gallery'
    | '/kindergarten'
    | '/news'
    | '/primary'
    | '/reset-password'
    | '/school-life'
    | '/sitemap.xml'
    | '/stages'
    | '/_authenticated/dashboard'
    | '/_authenticated/my-applications'
    | '/_authenticated/profile'
    | '/admissions/'
    | '/_authenticated/admin/audit'
    | '/_authenticated/admin/users'
    | '/_authenticated/ams/queue'
    | '/_authenticated/ams/reports'
    | '/_authenticated/ams/seats'
    | '/_authenticated/ams/waiting-list'
    | '/_authenticated/apply/$applicationId'
    | '/_authenticated/apply/new'
    | '/_authenticated/track/$applicationId'
    | '/_authenticated/ams/'
    | '/_authenticated/ams/applications/$applicationId'
    | '/admissions/stage/$slug/classrooms'
    | '/admissions/stage/$slug/'
    | '/admissions/stage/$slug/classroom/$classroomSlug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  GalleryRoute: typeof GalleryRoute
  KindergartenRoute: typeof KindergartenRoute
  NewsRoute: typeof NewsRoute
  PrimaryRoute: typeof PrimaryRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SchoolLifeRoute: typeof SchoolLifeRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StagesRoute: typeof StagesRoute
  AdmissionsIndexRoute: typeof AdmissionsIndexRoute
  AdmissionsStageSlugClassroomsRoute: typeof AdmissionsStageSlugClassroomsRoute
  AdmissionsStageSlugIndexRoute: typeof AdmissionsStageSlugIndexRoute
  AdmissionsStageSlugClassroomClassroomSlugRoute: typeof AdmissionsStageSlugClassroomClassroomSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stages': {
      id: '/stages'
      path: '/stages'
      fullPath: '/stages'
      preLoaderRoute: typeof StagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/school-life': {
      id: '/school-life'
      path: '/school-life'
      fullPath: '/school-life'
      preLoaderRoute: typeof SchoolLifeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/primary': {
      id: '/primary'
      path: '/primary'
      fullPath: '/primary'
      preLoaderRoute: typeof PrimaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kindergarten': {
      id: '/kindergarten'
      path: '/kindergarten'
      fullPath: '/kindergarten'
      preLoaderRoute: typeof KindergartenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admissions/': {
      id: '/admissions/'
      path: '/admissions'
      fullPath: '/admissions/'
      preLoaderRoute: typeof AdmissionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/my-applications': {
      id: '/_authenticated/my-applications'
      path: '/my-applications'
      fullPath: '/my-applications'
      preLoaderRoute: typeof AuthenticatedMyApplicationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ams/': {
      id: '/_authenticated/ams/'
      path: '/ams'
      fullPath: '/ams/'
      preLoaderRoute: typeof AuthenticatedAmsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/track/$applicationId': {
      id: '/_authenticated/track/$applicationId'
      path: '/track/$applicationId'
      fullPath: '/track/$applicationId'
      preLoaderRoute: typeof AuthenticatedTrackApplicationIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/apply/new': {
      id: '/_authenticated/apply/new'
      path: '/apply/new'
      fullPath: '/apply/new'
      preLoaderRoute: typeof AuthenticatedApplyNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/apply/$applicationId': {
      id: '/_authenticated/apply/$applicationId'
      path: '/apply/$applicationId'
      fullPath: '/apply/$applicationId'
      preLoaderRoute: typeof AuthenticatedApplyApplicationIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ams/waiting-list': {
      id: '/_authenticated/ams/waiting-list'
      path: '/ams/waiting-list'
      fullPath: '/ams/waiting-list'
      preLoaderRoute: typeof AuthenticatedAmsWaitingListRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ams/seats': {
      id: '/_authenticated/ams/seats'
      path: '/ams/seats'
      fullPath: '/ams/seats'
      preLoaderRoute: typeof AuthenticatedAmsSeatsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ams/reports': {
      id: '/_authenticated/ams/reports'
      path: '/ams/reports'
      fullPath: '/ams/reports'
      preLoaderRoute: typeof AuthenticatedAmsReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ams/queue': {
      id: '/_authenticated/ams/queue'
      path: '/ams/queue'
      fullPath: '/ams/queue'
      preLoaderRoute: typeof AuthenticatedAmsQueueRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/audit': {
      id: '/_authenticated/admin/audit'
      path: '/admin/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AuthenticatedAdminAuditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/admissions/stage/$slug/': {
      id: '/admissions/stage/$slug/'
      path: '/admissions/stage/$slug'
      fullPath: '/admissions/stage/$slug/'
      preLoaderRoute: typeof AdmissionsStageSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admissions/stage/$slug/classrooms': {
      id: '/admissions/stage/$slug/classrooms'
      path: '/admissions/stage/$slug/classrooms'
      fullPath: '/admissions/stage/$slug/classrooms'
      preLoaderRoute: typeof AdmissionsStageSlugClassroomsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/ams/applications/$applicationId': {
      id: '/_authenticated/ams/applications/$applicationId'
      path: '/ams/applications/$applicationId'
      fullPath: '/ams/applications/$applicationId'
      preLoaderRoute: typeof AuthenticatedAmsApplicationsApplicationIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/admissions/stage/$slug/classroom/$classroomSlug': {
      id: '/admissions/stage/$slug/classroom/$classroomSlug'
      path: '/admissions/stage/$slug/classroom/$classroomSlug'
      fullPath: '/admissions/stage/$slug/classroom/$classroomSlug'
      preLoaderRoute: typeof AdmissionsStageSlugClassroomClassroomSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedMyApplicationsRoute: typeof AuthenticatedMyApplicationsRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedAdminAuditRoute: typeof AuthenticatedAdminAuditRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAmsQueueRoute: typeof AuthenticatedAmsQueueRoute
  AuthenticatedAmsReportsRoute: typeof AuthenticatedAmsReportsRoute
  AuthenticatedAmsSeatsRoute: typeof AuthenticatedAmsSeatsRoute
  AuthenticatedAmsWaitingListRoute: typeof AuthenticatedAmsWaitingListRoute
  AuthenticatedApplyApplicationIdRoute: typeof AuthenticatedApplyApplicationIdRoute
  AuthenticatedApplyNewRoute: typeof AuthenticatedApplyNewRoute
  AuthenticatedTrackApplicationIdRoute: typeof AuthenticatedTrackApplicationIdRoute
  AuthenticatedAmsIndexRoute: typeof AuthenticatedAmsIndexRoute
  AuthenticatedAmsApplicationsApplicationIdRoute: typeof AuthenticatedAmsApplicationsApplicationIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedMyApplicationsRoute: AuthenticatedMyApplicationsRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedAdminAuditRoute: AuthenticatedAdminAuditRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedAmsQueueRoute: AuthenticatedAmsQueueRoute,
  AuthenticatedAmsReportsRoute: AuthenticatedAmsReportsRoute,
  AuthenticatedAmsSeatsRoute: AuthenticatedAmsSeatsRoute,
  AuthenticatedAmsWaitingListRoute: AuthenticatedAmsWaitingListRoute,
  AuthenticatedApplyApplicationIdRoute: AuthenticatedApplyApplicationIdRoute,
  AuthenticatedApplyNewRoute: AuthenticatedApplyNewRoute,
  AuthenticatedTrackApplicationIdRoute: AuthenticatedTrackApplicationIdRoute,
  AuthenticatedAmsIndexRoute: AuthenticatedAmsIndexRoute,
  AuthenticatedAmsApplicationsApplicationIdRoute:
    AuthenticatedAmsApplicationsApplicationIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  GalleryRoute: GalleryRoute,
  KindergartenRoute: KindergartenRoute,
  NewsRoute: NewsRoute,
  PrimaryRoute: PrimaryRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SchoolLifeRoute: SchoolLifeRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StagesRoute: StagesRoute,
  AdmissionsIndexRoute: AdmissionsIndexRoute,
  AdmissionsStageSlugClassroomsRoute: AdmissionsStageSlugClassroomsRoute,
  AdmissionsStageSlugIndexRoute: AdmissionsStageSlugIndexRoute,
  AdmissionsStageSlugClassroomClassroomSlugRoute:
    AdmissionsStageSlugClassroomClassroomSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
