/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestimonialsRouteImport } from './routes/testimonials'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as StagesRouteImport } from './routes/stages'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SchoolLifeRouteImport } from './routes/school-life'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PrimaryRouteImport } from './routes/primary'
import { Route as NewsRouteImport } from './routes/news'
import { Route as KindergartenRouteImport } from './routes/kindergarten'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TrackIndexRouteImport } from './routes/track.index'
import { Route as AdmissionsIndexRouteImport } from './routes/admissions.index'
import { Route as LegalSlugRouteImport } from './routes/legal.$slug'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as AuthenticatedStudyPlansRouteImport } from './routes/_authenticated/study-plans'
import { Route as AuthenticatedReserveRouteImport } from './routes/_authenticated/reserve'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedPaymentsRouteImport } from './routes/_authenticated/payments'
import { Route as AuthenticatedMyApplicationsRouteImport } from './routes/_authenticated/my-applications'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedClassChatRouteImport } from './routes/_authenticated/class-chat'
import { Route as AuthenticatedChildReportsRouteImport } from './routes/_authenticated/child-reports'
import { Route as AuthenticatedChildFileRouteImport } from './routes/_authenticated/child-file'
import { Route as AuthenticatedAmsIndexRouteImport } from './routes/_authenticated/ams/index'
import { Route as ApiAmsBackupRouteImport } from './routes/api/ams/backup'
import { Route as AuthenticatedTrackApplicationIdRouteImport } from './routes/_authenticated/track.$applicationId'
import { Route as AuthenticatedApplyNewRouteImport } from './routes/_authenticated/apply.new'
import { Route as AuthenticatedApplyApplicationIdRouteImport } from './routes/_authenticated/apply.$applicationId'
import { Route as AuthenticatedAmsWaitingListRouteImport } from './routes/_authenticated/ams/waiting-list'
import { Route as AuthenticatedAmsSeatsRouteImport } from './routes/_authenticated/ams/seats'
import { Route as AuthenticatedAmsSeasonsRouteImport } from './routes/_authenticated/ams/seasons'
import { Route as AuthenticatedAmsReservationsRouteImport } from './routes/_authenticated/ams/reservations'
import { Route as AuthenticatedAmsReportsRouteImport } from './routes/_authenticated/ams/reports'
import { Route as AuthenticatedAmsQueueRouteImport } from './routes/_authenticated/ams/queue'
import { Route as AuthenticatedAmsFormBuilderRouteImport } from './routes/_authenticated/ams/form-builder'
import { Route as AuthenticatedAmsActivityRouteImport } from './routes/_authenticated/ams/activity'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin/users'
import { Route as AuthenticatedAdminSiteContentRouteImport } from './routes/_authenticated/admin/site-content'
import { Route as AuthenticatedAdminPermissionsRouteImport } from './routes/_authenticated/admin/permissions'
import { Route as AuthenticatedAdminInboxRouteImport } from './routes/_authenticated/admin/inbox'
import { Route as AuthenticatedAdminAuditRouteImport } from './routes/_authenticated/admin/audit'
import { Route as AdmissionsStageSlugIndexRouteImport } from './routes/admissions.stage.$slug.index'
import { Route as AuthenticatedAmsStudentsIndexRouteImport } from './routes/_authenticated/ams/students.index'
import { Route as AuthenticatedAmsFinanceIndexRouteImport } from './routes/_authenticated/ams/finance.index'
import { Route as AuthenticatedAmsAcademicsIndexRouteImport } from './routes/_authenticated/ams/academics.index'
import { Route as AdmissionsStageSlugClassroomsRouteImport } from './routes/admissions.stage.$slug.classrooms'
import { Route as AuthenticatedAmsStudentsRegistryRouteImport } from './routes/_authenticated/ams/students.registry'
import { Route as AuthenticatedAmsStudentsPromotionsRouteImport } from './routes/_authenticated/ams/students.promotions'
import { Route as AuthenticatedAmsStudentsGuardiansRouteImport } from './routes/_authenticated/ams/students.guardians'
import { Route as AuthenticatedAmsStudentsDataRouteImport } from './routes/_authenticated/ams/students.data'
import { Route as AuthenticatedAmsStudentsAttendanceRouteImport } from './routes/_authenticated/ams/students.attendance'
import { Route as AuthenticatedAmsStudentsChildIdRouteImport } from './routes/_authenticated/ams/students.$childId'
import { Route as AuthenticatedAmsFinanceSettingsRouteImport } from './routes/_authenticated/ams/finance.settings'
import { Route as AuthenticatedAmsFinanceReportsRouteImport } from './routes/_authenticated/ams/finance.reports'
import { Route as AuthenticatedAmsFinanceInvoicesRouteImport } from './routes/_authenticated/ams/finance.invoices'
import { Route as AuthenticatedAmsFinanceClaimsRouteImport } from './routes/_authenticated/ams/finance.claims'
import { Route as AuthenticatedAmsApplicationsApplicationIdRouteImport } from './routes/_authenticated/ams/applications.$applicationId'
import { Route as AuthenticatedAmsAcademicsSettingsRouteImport } from './routes/_authenticated/ams/academics.settings'
import { Route as AuthenticatedAmsAcademicsReportsRouteImport } from './routes/_authenticated/ams/academics.reports'
import { Route as AuthenticatedAmsAcademicsPlansRouteImport } from './routes/_authenticated/ams/academics.plans'
import { Route as AuthenticatedAmsAcademicsCurriculumRouteImport } from './routes/_authenticated/ams/academics.curriculum'
import { Route as AuthenticatedAmsAcademicsChatRouteImport } from './routes/_authenticated/ams/academics.chat'
import { Route as AuthenticatedAmsAcademicsCalendarRouteImport } from './routes/_authenticated/ams/academics.calendar'
import { Route as AuthenticatedAmsAcademicsAssignmentsRouteImport } from './routes/_authenticated/ams/academics.assignments'
import { Route as AuthenticatedAmsAcademicsAssessmentsRouteImport } from './routes/_authenticated/ams/academics.assessments'
import { Route as AuthenticatedAdminTeachersTeacherIdRouteImport } from './routes/_authenticated/admin/teachers.$teacherId'
import { Route as AdmissionsStageSlugClassroomClassroomSlugRouteImport } from './routes/admissions.stage.$slug.classroom.$classroomSlug'

const TestimonialsRoute = TestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const StagesRoute = StagesRouteImport.update({
  id: '/stages',
  path: '/stages',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SchoolLifeRoute = SchoolLifeRouteImport.update({
  id: '/school-life',
  path: '/school-life',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PrimaryRoute = PrimaryRouteImport.update({
  id: '/primary',
  path: '/primary',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const KindergartenRoute = KindergartenRouteImport.update({
  id: '/kindergarten',
  path: '/kindergarten',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackIndexRoute = TrackIndexRouteImport.update({
  id: '/track/',
  path: '/track/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmissionsIndexRoute = AdmissionsIndexRouteImport.update({
  id: '/admissions/',
  path: '/admissions/',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalSlugRoute = LegalSlugRouteImport.update({
  id: '/legal/$slug',
  path: '/legal/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedStudyPlansRoute = AuthenticatedStudyPlansRouteImport.update({
  id: '/study-plans',
  path: '/study-plans',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReserveRoute = AuthenticatedReserveRouteImport.update({
  id: '/reserve',
  path: '/reserve',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPaymentsRoute = AuthenticatedPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMyApplicationsRoute =
  AuthenticatedMyApplicationsRouteImport.update({
    id: '/my-applications',
    path: '/my-applications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClassChatRoute = AuthenticatedClassChatRouteImport.update({
  id: '/class-chat',
  path: '/class-chat',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChildReportsRoute =
  AuthenticatedChildReportsRouteImport.update({
    id: '/child-reports',
    path: '/child-reports',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChildFileRoute = AuthenticatedChildFileRouteImport.update({
  id: '/child-file',
  path: '/child-file',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAmsIndexRoute = AuthenticatedAmsIndexRouteImport.update({
  id: '/ams/',
  path: '/ams/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiAmsBackupRoute = ApiAmsBackupRouteImport.update({
  id: '/api/ams/backup',
  path: '/api/ams/backup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTrackApplicationIdRoute =
  AuthenticatedTrackApplicationIdRouteImport.update({
    id: '/track/$applicationId',
    path: '/track/$applicationId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedApplyNewRoute = AuthenticatedApplyNewRouteImport.update({
  id: '/apply/new',
  path: '/apply/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedApplyApplicationIdRoute =
  AuthenticatedApplyApplicationIdRouteImport.update({
    id: '/apply/$applicationId',
    path: '/apply/$applicationId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAmsWaitingListRoute =
  AuthenticatedAmsWaitingListRouteImport.update({
    id: '/ams/waiting-list',
    path: '/ams/waiting-list',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAmsSeatsRoute = AuthenticatedAmsSeatsRouteImport.update({
  id: '/ams/seats',
  path: '/ams/seats',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAmsSeasonsRoute = AuthenticatedAmsSeasonsRouteImport.update({
  id: '/ams/seasons',
  path: '/ams/seasons',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAmsReservationsRoute =
  AuthenticatedAmsReservationsRouteImport.update({
    id: '/ams/reservations',
    path: '/ams/reservations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAmsReportsRoute = AuthenticatedAmsReportsRouteImport.update({
  id: '/ams/reports',
  path: '/ams/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAmsQueueRoute = AuthenticatedAmsQueueRouteImport.update({
  id: '/ams/queue',
  path: '/ams/queue',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAmsFormBuilderRoute =
  AuthenticatedAmsFormBuilderRouteImport.update({
    id: '/ams/form-builder',
    path: '/ams/form-builder',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAmsActivityRoute =
  AuthenticatedAmsActivityRouteImport.update({
    id: '/ams/activity',
    path: '/ams/activity',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminSiteContentRoute =
  AuthenticatedAdminSiteContentRouteImport.update({
    id: '/admin/site-content',
    path: '/admin/site-content',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminPermissionsRoute =
  AuthenticatedAdminPermissionsRouteImport.update({
    id: '/admin/permissions',
    path: '/admin/permissions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminInboxRoute = AuthenticatedAdminInboxRouteImport.update({
  id: '/admin/inbox',
  path: '/admin/inbox',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminAuditRoute = AuthenticatedAdminAuditRouteImport.update({
  id: '/admin/audit',
  path: '/admin/audit',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AdmissionsStageSlugIndexRoute =
  AdmissionsStageSlugIndexRouteImport.update({
    id: '/admissions/stage/$slug/',
    path: '/admissions/stage/$slug/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAmsStudentsIndexRoute =
  AuthenticatedAmsStudentsIndexRouteImport.update({
    id: '/ams/students/',
    path: '/ams/students/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAmsFinanceIndexRoute =
  AuthenticatedAmsFinanceIndexRouteImport.update({
    id: '/ams/finance/',
    path: '/ams/finance/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAmsAcademicsIndexRoute =
  AuthenticatedAmsAcademicsIndexRouteImport.update({
    id: '/ams/academics/',
    path: '/ams/academics/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AdmissionsStageSlugClassroomsRoute =
  AdmissionsStageSlugClassroomsRouteImport.update({
    id: '/admissions/stage/$slug/classrooms',
    path: '/admissions/stage/$slug/classrooms',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAmsStudentsRegistryRoute =
  AuthenticatedAmsStudentsRegistryRouteImport.update({
    id: '/ams/students/registry',
    path: '/ams/students/registry',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAmsStudentsPromotionsRoute =
  AuthenticatedAmsStudentsPromotionsRouteImport.update({
    id: '/ams/students/promotions',
    path: '/ams/students/promotions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAmsStudentsGuardiansRoute =
  AuthenticatedAmsStudentsGuardiansRouteImport.update({
    id: '/ams/students/guardians',
    path: '/ams/students/guardians',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAmsStudentsDataRoute =
  AuthenticatedAmsStudentsDataRouteImport.update({
    id: '/ams/students/data',
    path: '/ams/students/data',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAmsStudentsAttendanceRoute =
  AuthenticatedAmsStudentsAttendanceRouteImport.update({
    id: '/ams/students/attendance',
    path: '/ams/students/attendance',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAmsStudentsChildIdRoute =
  AuthenticatedAmsStudentsChildIdRouteImport.update({
    id: '/ams/students/$childId',
    path: '/ams/students/$childId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAmsFinanceSettingsRoute =
  AuthenticatedAmsFinanceSettingsRouteImport.update({
    id: '/ams/finance/settings',
    path: '/ams/finance/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAmsFinanceReportsRoute =
  AuthenticatedAmsFinanceReportsRouteImport.update({
    id: '/ams/finance/reports',
    path: '/ams/finance/reports',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAmsFinanceInvoicesRoute =
  AuthenticatedAmsFinanceInvoicesRouteImport.update({
    id: '/ams/finance/invoices',
    path: '/ams/finance/invoices',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAmsFinanceClaimsRoute =
  AuthenticatedAmsFinanceClaimsRouteImport.update({
    id: '/ams/finance/claims',
    path: '/ams/finance/claims',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAmsApplicationsApplicationIdRoute =
  AuthenticatedAmsApplicationsApplicationIdRouteImport.update({
    id: '/ams/applications/$applicationId',
    path: '/ams/applications/$applicationId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAmsAcademicsSettingsRoute =
  AuthenticatedAmsAcademicsSettingsRouteImport.update({
    id: '/ams/academics/settings',
    path: '/ams/academics/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAmsAcademicsReportsRoute =
  AuthenticatedAmsAcademicsReportsRouteImport.update({
    id: '/ams/academics/reports',
    path: '/ams/academics/reports',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAmsAcademicsPlansRoute =
  AuthenticatedAmsAcademicsPlansRouteImport.update({
    id: '/ams/academics/plans',
    path: '/ams/academics/plans',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAmsAcademicsCurriculumRoute =
  AuthenticatedAmsAcademicsCurriculumRouteImport.update({
    id: '/ams/academics/curriculum',
    path: '/ams/academics/curriculum',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAmsAcademicsChatRoute =
  AuthenticatedAmsAcademicsChatRouteImport.update({
    id: '/ams/academics/chat',
    path: '/ams/academics/chat',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAmsAcademicsCalendarRoute =
  AuthenticatedAmsAcademicsCalendarRouteImport.update({
    id: '/ams/academics/calendar',
    path: '/ams/academics/calendar',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAmsAcademicsAssignmentsRoute =
  AuthenticatedAmsAcademicsAssignmentsRouteImport.update({
    id: '/ams/academics/assignments',
    path: '/ams/academics/assignments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAmsAcademicsAssessmentsRoute =
  AuthenticatedAmsAcademicsAssessmentsRouteImport.update({
    id: '/ams/academics/assessments',
    path: '/ams/academics/assessments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminTeachersTeacherIdRoute =
  AuthenticatedAdminTeachersTeacherIdRouteImport.update({
    id: '/admin/teachers/$teacherId',
    path: '/admin/teachers/$teacherId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AdmissionsStageSlugClassroomClassroomSlugRoute =
  AdmissionsStageSlugClassroomClassroomSlugRouteImport.update({
    id: '/admissions/stage/$slug/classroom/$classroomSlug',
    path: '/admissions/stage/$slug/classroom/$classroomSlug',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/gallery': typeof GalleryRoute
  '/kindergarten': typeof KindergartenRoute
  '/news': typeof NewsRoute
  '/primary': typeof PrimaryRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/school-life': typeof SchoolLifeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stages': typeof StagesRoute
  '/terms': typeof TermsRoute
  '/testimonials': typeof TestimonialsRoute
  '/child-file': typeof AuthenticatedChildFileRoute
  '/child-reports': typeof AuthenticatedChildReportsRoute
  '/class-chat': typeof AuthenticatedClassChatRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/my-applications': typeof AuthenticatedMyApplicationsRoute
  '/payments': typeof AuthenticatedPaymentsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/reserve': typeof AuthenticatedReserveRoute
  '/study-plans': typeof AuthenticatedStudyPlansRoute
  '/invite/$token': typeof InviteTokenRoute
  '/legal/$slug': typeof LegalSlugRoute
  '/admissions/': typeof AdmissionsIndexRoute
  '/track/': typeof TrackIndexRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/inbox': typeof AuthenticatedAdminInboxRoute
  '/admin/permissions': typeof AuthenticatedAdminPermissionsRoute
  '/admin/site-content': typeof AuthenticatedAdminSiteContentRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/ams/activity': typeof AuthenticatedAmsActivityRoute
  '/ams/form-builder': typeof AuthenticatedAmsFormBuilderRoute
  '/ams/queue': typeof AuthenticatedAmsQueueRoute
  '/ams/reports': typeof AuthenticatedAmsReportsRoute
  '/ams/reservations': typeof AuthenticatedAmsReservationsRoute
  '/ams/seasons': typeof AuthenticatedAmsSeasonsRoute
  '/ams/seats': typeof AuthenticatedAmsSeatsRoute
  '/ams/waiting-list': typeof AuthenticatedAmsWaitingListRoute
  '/apply/$applicationId': typeof AuthenticatedApplyApplicationIdRoute
  '/apply/new': typeof AuthenticatedApplyNewRoute
  '/track/$applicationId': typeof AuthenticatedTrackApplicationIdRoute
  '/api/ams/backup': typeof ApiAmsBackupRoute
  '/ams/': typeof AuthenticatedAmsIndexRoute
  '/admin/teachers/$teacherId': typeof AuthenticatedAdminTeachersTeacherIdRoute
  '/ams/academics/assessments': typeof AuthenticatedAmsAcademicsAssessmentsRoute
  '/ams/academics/assignments': typeof AuthenticatedAmsAcademicsAssignmentsRoute
  '/ams/academics/calendar': typeof AuthenticatedAmsAcademicsCalendarRoute
  '/ams/academics/chat': typeof AuthenticatedAmsAcademicsChatRoute
  '/ams/academics/curriculum': typeof AuthenticatedAmsAcademicsCurriculumRoute
  '/ams/academics/plans': typeof AuthenticatedAmsAcademicsPlansRoute
  '/ams/academics/reports': typeof AuthenticatedAmsAcademicsReportsRoute
  '/ams/academics/settings': typeof AuthenticatedAmsAcademicsSettingsRoute
  '/ams/applications/$applicationId': typeof AuthenticatedAmsApplicationsApplicationIdRoute
  '/ams/finance/claims': typeof AuthenticatedAmsFinanceClaimsRoute
  '/ams/finance/invoices': typeof AuthenticatedAmsFinanceInvoicesRoute
  '/ams/finance/reports': typeof AuthenticatedAmsFinanceReportsRoute
  '/ams/finance/settings': typeof AuthenticatedAmsFinanceSettingsRoute
  '/ams/students/$childId': typeof AuthenticatedAmsStudentsChildIdRoute
  '/ams/students/attendance': typeof AuthenticatedAmsStudentsAttendanceRoute
  '/ams/students/data': typeof AuthenticatedAmsStudentsDataRoute
  '/ams/students/guardians': typeof AuthenticatedAmsStudentsGuardiansRoute
  '/ams/students/promotions': typeof AuthenticatedAmsStudentsPromotionsRoute
  '/ams/students/registry': typeof AuthenticatedAmsStudentsRegistryRoute
  '/admissions/stage/$slug/classrooms': typeof AdmissionsStageSlugClassroomsRoute
  '/ams/academics/': typeof AuthenticatedAmsAcademicsIndexRoute
  '/ams/finance/': typeof AuthenticatedAmsFinanceIndexRoute
  '/ams/students/': typeof AuthenticatedAmsStudentsIndexRoute
  '/admissions/stage/$slug/': typeof AdmissionsStageSlugIndexRoute
  '/admissions/stage/$slug/classroom/$classroomSlug': typeof AdmissionsStageSlugClassroomClassroomSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/gallery': typeof GalleryRoute
  '/kindergarten': typeof KindergartenRoute
  '/news': typeof NewsRoute
  '/primary': typeof PrimaryRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/school-life': typeof SchoolLifeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stages': typeof StagesRoute
  '/terms': typeof TermsRoute
  '/testimonials': typeof TestimonialsRoute
  '/child-file': typeof AuthenticatedChildFileRoute
  '/child-reports': typeof AuthenticatedChildReportsRoute
  '/class-chat': typeof AuthenticatedClassChatRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/my-applications': typeof AuthenticatedMyApplicationsRoute
  '/payments': typeof AuthenticatedPaymentsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/reserve': typeof AuthenticatedReserveRoute
  '/study-plans': typeof AuthenticatedStudyPlansRoute
  '/invite/$token': typeof InviteTokenRoute
  '/legal/$slug': typeof LegalSlugRoute
  '/admissions': typeof AdmissionsIndexRoute
  '/track': typeof TrackIndexRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/inbox': typeof AuthenticatedAdminInboxRoute
  '/admin/permissions': typeof AuthenticatedAdminPermissionsRoute
  '/admin/site-content': typeof AuthenticatedAdminSiteContentRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/ams/activity': typeof AuthenticatedAmsActivityRoute
  '/ams/form-builder': typeof AuthenticatedAmsFormBuilderRoute
  '/ams/queue': typeof AuthenticatedAmsQueueRoute
  '/ams/reports': typeof AuthenticatedAmsReportsRoute
  '/ams/reservations': typeof AuthenticatedAmsReservationsRoute
  '/ams/seasons': typeof AuthenticatedAmsSeasonsRoute
  '/ams/seats': typeof AuthenticatedAmsSeatsRoute
  '/ams/waiting-list': typeof AuthenticatedAmsWaitingListRoute
  '/apply/$applicationId': typeof AuthenticatedApplyApplicationIdRoute
  '/apply/new': typeof AuthenticatedApplyNewRoute
  '/track/$applicationId': typeof AuthenticatedTrackApplicationIdRoute
  '/api/ams/backup': typeof ApiAmsBackupRoute
  '/ams': typeof AuthenticatedAmsIndexRoute
  '/admin/teachers/$teacherId': typeof AuthenticatedAdminTeachersTeacherIdRoute
  '/ams/academics/assessments': typeof AuthenticatedAmsAcademicsAssessmentsRoute
  '/ams/academics/assignments': typeof AuthenticatedAmsAcademicsAssignmentsRoute
  '/ams/academics/calendar': typeof AuthenticatedAmsAcademicsCalendarRoute
  '/ams/academics/chat': typeof AuthenticatedAmsAcademicsChatRoute
  '/ams/academics/curriculum': typeof AuthenticatedAmsAcademicsCurriculumRoute
  '/ams/academics/plans': typeof AuthenticatedAmsAcademicsPlansRoute
  '/ams/academics/reports': typeof AuthenticatedAmsAcademicsReportsRoute
  '/ams/academics/settings': typeof AuthenticatedAmsAcademicsSettingsRoute
  '/ams/applications/$applicationId': typeof AuthenticatedAmsApplicationsApplicationIdRoute
  '/ams/finance/claims': typeof AuthenticatedAmsFinanceClaimsRoute
  '/ams/finance/invoices': typeof AuthenticatedAmsFinanceInvoicesRoute
  '/ams/finance/reports': typeof AuthenticatedAmsFinanceReportsRoute
  '/ams/finance/settings': typeof AuthenticatedAmsFinanceSettingsRoute
  '/ams/students/$childId': typeof AuthenticatedAmsStudentsChildIdRoute
  '/ams/students/attendance': typeof AuthenticatedAmsStudentsAttendanceRoute
  '/ams/students/data': typeof AuthenticatedAmsStudentsDataRoute
  '/ams/students/guardians': typeof AuthenticatedAmsStudentsGuardiansRoute
  '/ams/students/promotions': typeof AuthenticatedAmsStudentsPromotionsRoute
  '/ams/students/registry': typeof AuthenticatedAmsStudentsRegistryRoute
  '/admissions/stage/$slug/classrooms': typeof AdmissionsStageSlugClassroomsRoute
  '/ams/academics': typeof AuthenticatedAmsAcademicsIndexRoute
  '/ams/finance': typeof AuthenticatedAmsFinanceIndexRoute
  '/ams/students': typeof AuthenticatedAmsStudentsIndexRoute
  '/admissions/stage/$slug': typeof AdmissionsStageSlugIndexRoute
  '/admissions/stage/$slug/classroom/$classroomSlug': typeof AdmissionsStageSlugClassroomClassroomSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/gallery': typeof GalleryRoute
  '/kindergarten': typeof KindergartenRoute
  '/news': typeof NewsRoute
  '/primary': typeof PrimaryRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/school-life': typeof SchoolLifeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/stages': typeof StagesRoute
  '/terms': typeof TermsRoute
  '/testimonials': typeof TestimonialsRoute
  '/_authenticated/child-file': typeof AuthenticatedChildFileRoute
  '/_authenticated/child-reports': typeof AuthenticatedChildReportsRoute
  '/_authenticated/class-chat': typeof AuthenticatedClassChatRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/my-applications': typeof AuthenticatedMyApplicationsRoute
  '/_authenticated/payments': typeof AuthenticatedPaymentsRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/reserve': typeof AuthenticatedReserveRoute
  '/_authenticated/study-plans': typeof AuthenticatedStudyPlansRoute
  '/invite/$token': typeof InviteTokenRoute
  '/legal/$slug': typeof LegalSlugRoute
  '/admissions/': typeof AdmissionsIndexRoute
  '/track/': typeof TrackIndexRoute
  '/_authenticated/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/_authenticated/admin/inbox': typeof AuthenticatedAdminInboxRoute
  '/_authenticated/admin/permissions': typeof AuthenticatedAdminPermissionsRoute
  '/_authenticated/admin/site-content': typeof AuthenticatedAdminSiteContentRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/ams/activity': typeof AuthenticatedAmsActivityRoute
  '/_authenticated/ams/form-builder': typeof AuthenticatedAmsFormBuilderRoute
  '/_authenticated/ams/queue': typeof AuthenticatedAmsQueueRoute
  '/_authenticated/ams/reports': typeof AuthenticatedAmsReportsRoute
  '/_authenticated/ams/reservations': typeof AuthenticatedAmsReservationsRoute
  '/_authenticated/ams/seasons': typeof AuthenticatedAmsSeasonsRoute
  '/_authenticated/ams/seats': typeof AuthenticatedAmsSeatsRoute
  '/_authenticated/ams/waiting-list': typeof AuthenticatedAmsWaitingListRoute
  '/_authenticated/apply/$applicationId': typeof AuthenticatedApplyApplicationIdRoute
  '/_authenticated/apply/new': typeof AuthenticatedApplyNewRoute
  '/_authenticated/track/$applicationId': typeof AuthenticatedTrackApplicationIdRoute
  '/api/ams/backup': typeof ApiAmsBackupRoute
  '/_authenticated/ams/': typeof AuthenticatedAmsIndexRoute
  '/_authenticated/admin/teachers/$teacherId': typeof AuthenticatedAdminTeachersTeacherIdRoute
  '/_authenticated/ams/academics/assessments': typeof AuthenticatedAmsAcademicsAssessmentsRoute
  '/_authenticated/ams/academics/assignments': typeof AuthenticatedAmsAcademicsAssignmentsRoute
  '/_authenticated/ams/academics/calendar': typeof AuthenticatedAmsAcademicsCalendarRoute
  '/_authenticated/ams/academics/chat': typeof AuthenticatedAmsAcademicsChatRoute
  '/_authenticated/ams/academics/curriculum': typeof AuthenticatedAmsAcademicsCurriculumRoute
  '/_authenticated/ams/academics/plans': typeof AuthenticatedAmsAcademicsPlansRoute
  '/_authenticated/ams/academics/reports': typeof AuthenticatedAmsAcademicsReportsRoute
  '/_authenticated/ams/academics/settings': typeof AuthenticatedAmsAcademicsSettingsRoute
  '/_authenticated/ams/applications/$applicationId': typeof AuthenticatedAmsApplicationsApplicationIdRoute
  '/_authenticated/ams/finance/claims': typeof AuthenticatedAmsFinanceClaimsRoute
  '/_authenticated/ams/finance/invoices': typeof AuthenticatedAmsFinanceInvoicesRoute
  '/_authenticated/ams/finance/reports': typeof AuthenticatedAmsFinanceReportsRoute
  '/_authenticated/ams/finance/settings': typeof AuthenticatedAmsFinanceSettingsRoute
  '/_authenticated/ams/students/$childId': typeof AuthenticatedAmsStudentsChildIdRoute
  '/_authenticated/ams/students/attendance': typeof AuthenticatedAmsStudentsAttendanceRoute
  '/_authenticated/ams/students/data': typeof AuthenticatedAmsStudentsDataRoute
  '/_authenticated/ams/students/guardians': typeof AuthenticatedAmsStudentsGuardiansRoute
  '/_authenticated/ams/students/promotions': typeof AuthenticatedAmsStudentsPromotionsRoute
  '/_authenticated/ams/students/registry': typeof AuthenticatedAmsStudentsRegistryRoute
  '/admissions/stage/$slug/classrooms': typeof AdmissionsStageSlugClassroomsRoute
  '/_authenticated/ams/academics/': typeof AuthenticatedAmsAcademicsIndexRoute
  '/_authenticated/ams/finance/': typeof AuthenticatedAmsFinanceIndexRoute
  '/_authenticated/ams/students/': typeof AuthenticatedAmsStudentsIndexRoute
  '/admissions/stage/$slug/': typeof AdmissionsStageSlugIndexRoute
  '/admissions/stage/$slug/classroom/$classroomSlug': typeof AdmissionsStageSlugClassroomClassroomSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/faq'
    | '/forgot-password'
    | '/gallery'
    | '/kindergarten'
    | '/news'
    | '/primary'
    | '/privacy'
    | '/reset-password'
    | '/school-life'
    | '/sitemap.xml'
    | '/stages'
    | '/terms'
    | '/testimonials'
    | '/child-file'
    | '/child-reports'
    | '/class-chat'
    | '/dashboard'
    | '/my-applications'
    | '/payments'
    | '/profile'
    | '/reserve'
    | '/study-plans'
    | '/invite/$token'
    | '/legal/$slug'
    | '/admissions/'
    | '/track/'
    | '/admin/audit'
    | '/admin/inbox'
    | '/admin/permissions'
    | '/admin/site-content'
    | '/admin/users'
    | '/ams/activity'
    | '/ams/form-builder'
    | '/ams/queue'
    | '/ams/reports'
    | '/ams/reservations'
    | '/ams/seasons'
    | '/ams/seats'
    | '/ams/waiting-list'
    | '/apply/$applicationId'
    | '/apply/new'
    | '/track/$applicationId'
    | '/api/ams/backup'
    | '/ams/'
    | '/admin/teachers/$teacherId'
    | '/ams/academics/assessments'
    | '/ams/academics/assignments'
    | '/ams/academics/calendar'
    | '/ams/academics/chat'
    | '/ams/academics/curriculum'
    | '/ams/academics/plans'
    | '/ams/academics/reports'
    | '/ams/academics/settings'
    | '/ams/applications/$applicationId'
    | '/ams/finance/claims'
    | '/ams/finance/invoices'
    | '/ams/finance/reports'
    | '/ams/finance/settings'
    | '/ams/students/$childId'
    | '/ams/students/attendance'
    | '/ams/students/data'
    | '/ams/students/guardians'
    | '/ams/students/promotions'
    | '/ams/students/registry'
    | '/admissions/stage/$slug/classrooms'
    | '/ams/academics/'
    | '/ams/finance/'
    | '/ams/students/'
    | '/admissions/stage/$slug/'
    | '/admissions/stage/$slug/classroom/$classroomSlug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/faq'
    | '/forgot-password'
    | '/gallery'
    | '/kindergarten'
    | '/news'
    | '/primary'
    | '/privacy'
    | '/reset-password'
    | '/school-life'
    | '/sitemap.xml'
    | '/stages'
    | '/terms'
    | '/testimonials'
    | '/child-file'
    | '/child-reports'
    | '/class-chat'
    | '/dashboard'
    | '/my-applications'
    | '/payments'
    | '/profile'
    | '/reserve'
    | '/study-plans'
    | '/invite/$token'
    | '/legal/$slug'
    | '/admissions'
    | '/track'
    | '/admin/audit'
    | '/admin/inbox'
    | '/admin/permissions'
    | '/admin/site-content'
    | '/admin/users'
    | '/ams/activity'
    | '/ams/form-builder'
    | '/ams/queue'
    | '/ams/reports'
    | '/ams/reservations'
    | '/ams/seasons'
    | '/ams/seats'
    | '/ams/waiting-list'
    | '/apply/$applicationId'
    | '/apply/new'
    | '/track/$applicationId'
    | '/api/ams/backup'
    | '/ams'
    | '/admin/teachers/$teacherId'
    | '/ams/academics/assessments'
    | '/ams/academics/assignments'
    | '/ams/academics/calendar'
    | '/ams/academics/chat'
    | '/ams/academics/curriculum'
    | '/ams/academics/plans'
    | '/ams/academics/reports'
    | '/ams/academics/settings'
    | '/ams/applications/$applicationId'
    | '/ams/finance/claims'
    | '/ams/finance/invoices'
    | '/ams/finance/reports'
    | '/ams/finance/settings'
    | '/ams/students/$childId'
    | '/ams/students/attendance'
    | '/ams/students/data'
    | '/ams/students/guardians'
    | '/ams/students/promotions'
    | '/ams/students/registry'
    | '/admissions/stage/$slug/classrooms'
    | '/ams/academics'
    | '/ams/finance'
    | '/ams/students'
    | '/admissions/stage/$slug'
    | '/admissions/stage/$slug/classroom/$classroomSlug'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/contact'
    | '/faq'
    | '/forgot-password'
    | '/gallery'
    | '/kindergarten'
    | '/news'
    | '/primary'
    | '/privacy'
    | '/reset-password'
    | '/school-life'
    | '/sitemap.xml'
    | '/stages'
    | '/terms'
    | '/testimonials'
    | '/_authenticated/child-file'
    | '/_authenticated/child-reports'
    | '/_authenticated/class-chat'
    | '/_authenticated/dashboard'
    | '/_authenticated/my-applications'
    | '/_authenticated/payments'
    | '/_authenticated/profile'
    | '/_authenticated/reserve'
    | '/_authenticated/study-plans'
    | '/invite/$token'
    | '/legal/$slug'
    | '/admissions/'
    | '/track/'
    | '/_authenticated/admin/audit'
    | '/_authenticated/admin/inbox'
    | '/_authenticated/admin/permissions'
    | '/_authenticated/admin/site-content'
    | '/_authenticated/admin/users'
    | '/_authenticated/ams/activity'
    | '/_authenticated/ams/form-builder'
    | '/_authenticated/ams/queue'
    | '/_authenticated/ams/reports'
    | '/_authenticated/ams/reservations'
    | '/_authenticated/ams/seasons'
    | '/_authenticated/ams/seats'
    | '/_authenticated/ams/waiting-list'
    | '/_authenticated/apply/$applicationId'
    | '/_authenticated/apply/new'
    | '/_authenticated/track/$applicationId'
    | '/api/ams/backup'
    | '/_authenticated/ams/'
    | '/_authenticated/admin/teachers/$teacherId'
    | '/_authenticated/ams/academics/assessments'
    | '/_authenticated/ams/academics/assignments'
    | '/_authenticated/ams/academics/calendar'
    | '/_authenticated/ams/academics/chat'
    | '/_authenticated/ams/academics/curriculum'
    | '/_authenticated/ams/academics/plans'
    | '/_authenticated/ams/academics/reports'
    | '/_authenticated/ams/academics/settings'
    | '/_authenticated/ams/applications/$applicationId'
    | '/_authenticated/ams/finance/claims'
    | '/_authenticated/ams/finance/invoices'
    | '/_authenticated/ams/finance/reports'
    | '/_authenticated/ams/finance/settings'
    | '/_authenticated/ams/students/$childId'
    | '/_authenticated/ams/students/attendance'
    | '/_authenticated/ams/students/data'
    | '/_authenticated/ams/students/guardians'
    | '/_authenticated/ams/students/promotions'
    | '/_authenticated/ams/students/registry'
    | '/admissions/stage/$slug/classrooms'
    | '/_authenticated/ams/academics/'
    | '/_authenticated/ams/finance/'
    | '/_authenticated/ams/students/'
    | '/admissions/stage/$slug/'
    | '/admissions/stage/$slug/classroom/$classroomSlug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  GalleryRoute: typeof GalleryRoute
  KindergartenRoute: typeof KindergartenRoute
  NewsRoute: typeof NewsRoute
  PrimaryRoute: typeof PrimaryRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SchoolLifeRoute: typeof SchoolLifeRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StagesRoute: typeof StagesRoute
  TermsRoute: typeof TermsRoute
  TestimonialsRoute: typeof TestimonialsRoute
  InviteTokenRoute: typeof InviteTokenRoute
  LegalSlugRoute: typeof LegalSlugRoute
  AdmissionsIndexRoute: typeof AdmissionsIndexRoute
  TrackIndexRoute: typeof TrackIndexRoute
  ApiAmsBackupRoute: typeof ApiAmsBackupRoute
  AdmissionsStageSlugClassroomsRoute: typeof AdmissionsStageSlugClassroomsRoute
  AdmissionsStageSlugIndexRoute: typeof AdmissionsStageSlugIndexRoute
  AdmissionsStageSlugClassroomClassroomSlugRoute: typeof AdmissionsStageSlugClassroomClassroomSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/testimonials': {
      id: '/testimonials'
      path: '/testimonials'
      fullPath: '/testimonials'
      preLoaderRoute: typeof TestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stages': {
      id: '/stages'
      path: '/stages'
      fullPath: '/stages'
      preLoaderRoute: typeof StagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/school-life': {
      id: '/school-life'
      path: '/school-life'
      fullPath: '/school-life'
      preLoaderRoute: typeof SchoolLifeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/primary': {
      id: '/primary'
      path: '/primary'
      fullPath: '/primary'
      preLoaderRoute: typeof PrimaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kindergarten': {
      id: '/kindergarten'
      path: '/kindergarten'
      fullPath: '/kindergarten'
      preLoaderRoute: typeof KindergartenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track/': {
      id: '/track/'
      path: '/track'
      fullPath: '/track/'
      preLoaderRoute: typeof TrackIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admissions/': {
      id: '/admissions/'
      path: '/admissions'
      fullPath: '/admissions/'
      preLoaderRoute: typeof AdmissionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/$slug': {
      id: '/legal/$slug'
      path: '/legal/$slug'
      fullPath: '/legal/$slug'
      preLoaderRoute: typeof LegalSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/study-plans': {
      id: '/_authenticated/study-plans'
      path: '/study-plans'
      fullPath: '/study-plans'
      preLoaderRoute: typeof AuthenticatedStudyPlansRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reserve': {
      id: '/_authenticated/reserve'
      path: '/reserve'
      fullPath: '/reserve'
      preLoaderRoute: typeof AuthenticatedReserveRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/payments': {
      id: '/_authenticated/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof AuthenticatedPaymentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/my-applications': {
      id: '/_authenticated/my-applications'
      path: '/my-applications'
      fullPath: '/my-applications'
      preLoaderRoute: typeof AuthenticatedMyApplicationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/class-chat': {
      id: '/_authenticated/class-chat'
      path: '/class-chat'
      fullPath: '/class-chat'
      preLoaderRoute: typeof AuthenticatedClassChatRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/child-reports': {
      id: '/_authenticated/child-reports'
      path: '/child-reports'
      fullPath: '/child-reports'
      preLoaderRoute: typeof AuthenticatedChildReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/child-file': {
      id: '/_authenticated/child-file'
      path: '/child-file'
      fullPath: '/child-file'
      preLoaderRoute: typeof AuthenticatedChildFileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ams/': {
      id: '/_authenticated/ams/'
      path: '/ams'
      fullPath: '/ams/'
      preLoaderRoute: typeof AuthenticatedAmsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/ams/backup': {
      id: '/api/ams/backup'
      path: '/api/ams/backup'
      fullPath: '/api/ams/backup'
      preLoaderRoute: typeof ApiAmsBackupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/track/$applicationId': {
      id: '/_authenticated/track/$applicationId'
      path: '/track/$applicationId'
      fullPath: '/track/$applicationId'
      preLoaderRoute: typeof AuthenticatedTrackApplicationIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/apply/new': {
      id: '/_authenticated/apply/new'
      path: '/apply/new'
      fullPath: '/apply/new'
      preLoaderRoute: typeof AuthenticatedApplyNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/apply/$applicationId': {
      id: '/_authenticated/apply/$applicationId'
      path: '/apply/$applicationId'
      fullPath: '/apply/$applicationId'
      preLoaderRoute: typeof AuthenticatedApplyApplicationIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ams/waiting-list': {
      id: '/_authenticated/ams/waiting-list'
      path: '/ams/waiting-list'
      fullPath: '/ams/waiting-list'
      preLoaderRoute: typeof AuthenticatedAmsWaitingListRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ams/seats': {
      id: '/_authenticated/ams/seats'
      path: '/ams/seats'
      fullPath: '/ams/seats'
      preLoaderRoute: typeof AuthenticatedAmsSeatsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ams/seasons': {
      id: '/_authenticated/ams/seasons'
      path: '/ams/seasons'
      fullPath: '/ams/seasons'
      preLoaderRoute: typeof AuthenticatedAmsSeasonsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ams/reservations': {
      id: '/_authenticated/ams/reservations'
      path: '/ams/reservations'
      fullPath: '/ams/reservations'
      preLoaderRoute: typeof AuthenticatedAmsReservationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ams/reports': {
      id: '/_authenticated/ams/reports'
      path: '/ams/reports'
      fullPath: '/ams/reports'
      preLoaderRoute: typeof AuthenticatedAmsReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ams/queue': {
      id: '/_authenticated/ams/queue'
      path: '/ams/queue'
      fullPath: '/ams/queue'
      preLoaderRoute: typeof AuthenticatedAmsQueueRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ams/form-builder': {
      id: '/_authenticated/ams/form-builder'
      path: '/ams/form-builder'
      fullPath: '/ams/form-builder'
      preLoaderRoute: typeof AuthenticatedAmsFormBuilderRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ams/activity': {
      id: '/_authenticated/ams/activity'
      path: '/ams/activity'
      fullPath: '/ams/activity'
      preLoaderRoute: typeof AuthenticatedAmsActivityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/site-content': {
      id: '/_authenticated/admin/site-content'
      path: '/admin/site-content'
      fullPath: '/admin/site-content'
      preLoaderRoute: typeof AuthenticatedAdminSiteContentRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/permissions': {
      id: '/_authenticated/admin/permissions'
      path: '/admin/permissions'
      fullPath: '/admin/permissions'
      preLoaderRoute: typeof AuthenticatedAdminPermissionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/inbox': {
      id: '/_authenticated/admin/inbox'
      path: '/admin/inbox'
      fullPath: '/admin/inbox'
      preLoaderRoute: typeof AuthenticatedAdminInboxRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/audit': {
      id: '/_authenticated/admin/audit'
      path: '/admin/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AuthenticatedAdminAuditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/admissions/stage/$slug/': {
      id: '/admissions/stage/$slug/'
      path: '/admissions/stage/$slug'
      fullPath: '/admissions/stage/$slug/'
      preLoaderRoute: typeof AdmissionsStageSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/ams/students/': {
      id: '/_authenticated/ams/students/'
      path: '/ams/students'
      fullPath: '/ams/students/'
      preLoaderRoute: typeof AuthenticatedAmsStudentsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ams/finance/': {
      id: '/_authenticated/ams/finance/'
      path: '/ams/finance'
      fullPath: '/ams/finance/'
      preLoaderRoute: typeof AuthenticatedAmsFinanceIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ams/academics/': {
      id: '/_authenticated/ams/academics/'
      path: '/ams/academics'
      fullPath: '/ams/academics/'
      preLoaderRoute: typeof AuthenticatedAmsAcademicsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/admissions/stage/$slug/classrooms': {
      id: '/admissions/stage/$slug/classrooms'
      path: '/admissions/stage/$slug/classrooms'
      fullPath: '/admissions/stage/$slug/classrooms'
      preLoaderRoute: typeof AdmissionsStageSlugClassroomsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/ams/students/registry': {
      id: '/_authenticated/ams/students/registry'
      path: '/ams/students/registry'
      fullPath: '/ams/students/registry'
      preLoaderRoute: typeof AuthenticatedAmsStudentsRegistryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ams/students/promotions': {
      id: '/_authenticated/ams/students/promotions'
      path: '/ams/students/promotions'
      fullPath: '/ams/students/promotions'
      preLoaderRoute: typeof AuthenticatedAmsStudentsPromotionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ams/students/guardians': {
      id: '/_authenticated/ams/students/guardians'
      path: '/ams/students/guardians'
      fullPath: '/ams/students/guardians'
      preLoaderRoute: typeof AuthenticatedAmsStudentsGuardiansRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ams/students/data': {
      id: '/_authenticated/ams/students/data'
      path: '/ams/students/data'
      fullPath: '/ams/students/data'
      preLoaderRoute: typeof AuthenticatedAmsStudentsDataRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ams/students/attendance': {
      id: '/_authenticated/ams/students/attendance'
      path: '/ams/students/attendance'
      fullPath: '/ams/students/attendance'
      preLoaderRoute: typeof AuthenticatedAmsStudentsAttendanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ams/students/$childId': {
      id: '/_authenticated/ams/students/$childId'
      path: '/ams/students/$childId'
      fullPath: '/ams/students/$childId'
      preLoaderRoute: typeof AuthenticatedAmsStudentsChildIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ams/finance/settings': {
      id: '/_authenticated/ams/finance/settings'
      path: '/ams/finance/settings'
      fullPath: '/ams/finance/settings'
      preLoaderRoute: typeof AuthenticatedAmsFinanceSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ams/finance/reports': {
      id: '/_authenticated/ams/finance/reports'
      path: '/ams/finance/reports'
      fullPath: '/ams/finance/reports'
      preLoaderRoute: typeof AuthenticatedAmsFinanceReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ams/finance/invoices': {
      id: '/_authenticated/ams/finance/invoices'
      path: '/ams/finance/invoices'
      fullPath: '/ams/finance/invoices'
      preLoaderRoute: typeof AuthenticatedAmsFinanceInvoicesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ams/finance/claims': {
      id: '/_authenticated/ams/finance/claims'
      path: '/ams/finance/claims'
      fullPath: '/ams/finance/claims'
      preLoaderRoute: typeof AuthenticatedAmsFinanceClaimsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ams/applications/$applicationId': {
      id: '/_authenticated/ams/applications/$applicationId'
      path: '/ams/applications/$applicationId'
      fullPath: '/ams/applications/$applicationId'
      preLoaderRoute: typeof AuthenticatedAmsApplicationsApplicationIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ams/academics/settings': {
      id: '/_authenticated/ams/academics/settings'
      path: '/ams/academics/settings'
      fullPath: '/ams/academics/settings'
      preLoaderRoute: typeof AuthenticatedAmsAcademicsSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ams/academics/reports': {
      id: '/_authenticated/ams/academics/reports'
      path: '/ams/academics/reports'
      fullPath: '/ams/academics/reports'
      preLoaderRoute: typeof AuthenticatedAmsAcademicsReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ams/academics/plans': {
      id: '/_authenticated/ams/academics/plans'
      path: '/ams/academics/plans'
      fullPath: '/ams/academics/plans'
      preLoaderRoute: typeof AuthenticatedAmsAcademicsPlansRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ams/academics/curriculum': {
      id: '/_authenticated/ams/academics/curriculum'
      path: '/ams/academics/curriculum'
      fullPath: '/ams/academics/curriculum'
      preLoaderRoute: typeof AuthenticatedAmsAcademicsCurriculumRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ams/academics/chat': {
      id: '/_authenticated/ams/academics/chat'
      path: '/ams/academics/chat'
      fullPath: '/ams/academics/chat'
      preLoaderRoute: typeof AuthenticatedAmsAcademicsChatRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ams/academics/calendar': {
      id: '/_authenticated/ams/academics/calendar'
      path: '/ams/academics/calendar'
      fullPath: '/ams/academics/calendar'
      preLoaderRoute: typeof AuthenticatedAmsAcademicsCalendarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ams/academics/assignments': {
      id: '/_authenticated/ams/academics/assignments'
      path: '/ams/academics/assignments'
      fullPath: '/ams/academics/assignments'
      preLoaderRoute: typeof AuthenticatedAmsAcademicsAssignmentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ams/academics/assessments': {
      id: '/_authenticated/ams/academics/assessments'
      path: '/ams/academics/assessments'
      fullPath: '/ams/academics/assessments'
      preLoaderRoute: typeof AuthenticatedAmsAcademicsAssessmentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/teachers/$teacherId': {
      id: '/_authenticated/admin/teachers/$teacherId'
      path: '/admin/teachers/$teacherId'
      fullPath: '/admin/teachers/$teacherId'
      preLoaderRoute: typeof AuthenticatedAdminTeachersTeacherIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/admissions/stage/$slug/classroom/$classroomSlug': {
      id: '/admissions/stage/$slug/classroom/$classroomSlug'
      path: '/admissions/stage/$slug/classroom/$classroomSlug'
      fullPath: '/admissions/stage/$slug/classroom/$classroomSlug'
      preLoaderRoute: typeof AdmissionsStageSlugClassroomClassroomSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedChildFileRoute: typeof AuthenticatedChildFileRoute
  AuthenticatedChildReportsRoute: typeof AuthenticatedChildReportsRoute
  AuthenticatedClassChatRoute: typeof AuthenticatedClassChatRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedMyApplicationsRoute: typeof AuthenticatedMyApplicationsRoute
  AuthenticatedPaymentsRoute: typeof AuthenticatedPaymentsRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedReserveRoute: typeof AuthenticatedReserveRoute
  AuthenticatedStudyPlansRoute: typeof AuthenticatedStudyPlansRoute
  AuthenticatedAdminAuditRoute: typeof AuthenticatedAdminAuditRoute
  AuthenticatedAdminInboxRoute: typeof AuthenticatedAdminInboxRoute
  AuthenticatedAdminPermissionsRoute: typeof AuthenticatedAdminPermissionsRoute
  AuthenticatedAdminSiteContentRoute: typeof AuthenticatedAdminSiteContentRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAmsActivityRoute: typeof AuthenticatedAmsActivityRoute
  AuthenticatedAmsFormBuilderRoute: typeof AuthenticatedAmsFormBuilderRoute
  AuthenticatedAmsQueueRoute: typeof AuthenticatedAmsQueueRoute
  AuthenticatedAmsReportsRoute: typeof AuthenticatedAmsReportsRoute
  AuthenticatedAmsReservationsRoute: typeof AuthenticatedAmsReservationsRoute
  AuthenticatedAmsSeasonsRoute: typeof AuthenticatedAmsSeasonsRoute
  AuthenticatedAmsSeatsRoute: typeof AuthenticatedAmsSeatsRoute
  AuthenticatedAmsWaitingListRoute: typeof AuthenticatedAmsWaitingListRoute
  AuthenticatedApplyApplicationIdRoute: typeof AuthenticatedApplyApplicationIdRoute
  AuthenticatedApplyNewRoute: typeof AuthenticatedApplyNewRoute
  AuthenticatedTrackApplicationIdRoute: typeof AuthenticatedTrackApplicationIdRoute
  AuthenticatedAmsIndexRoute: typeof AuthenticatedAmsIndexRoute
  AuthenticatedAdminTeachersTeacherIdRoute: typeof AuthenticatedAdminTeachersTeacherIdRoute
  AuthenticatedAmsAcademicsAssessmentsRoute: typeof AuthenticatedAmsAcademicsAssessmentsRoute
  AuthenticatedAmsAcademicsAssignmentsRoute: typeof AuthenticatedAmsAcademicsAssignmentsRoute
  AuthenticatedAmsAcademicsCalendarRoute: typeof AuthenticatedAmsAcademicsCalendarRoute
  AuthenticatedAmsAcademicsChatRoute: typeof AuthenticatedAmsAcademicsChatRoute
  AuthenticatedAmsAcademicsCurriculumRoute: typeof AuthenticatedAmsAcademicsCurriculumRoute
  AuthenticatedAmsAcademicsPlansRoute: typeof AuthenticatedAmsAcademicsPlansRoute
  AuthenticatedAmsAcademicsReportsRoute: typeof AuthenticatedAmsAcademicsReportsRoute
  AuthenticatedAmsAcademicsSettingsRoute: typeof AuthenticatedAmsAcademicsSettingsRoute
  AuthenticatedAmsApplicationsApplicationIdRoute: typeof AuthenticatedAmsApplicationsApplicationIdRoute
  AuthenticatedAmsFinanceClaimsRoute: typeof AuthenticatedAmsFinanceClaimsRoute
  AuthenticatedAmsFinanceInvoicesRoute: typeof AuthenticatedAmsFinanceInvoicesRoute
  AuthenticatedAmsFinanceReportsRoute: typeof AuthenticatedAmsFinanceReportsRoute
  AuthenticatedAmsFinanceSettingsRoute: typeof AuthenticatedAmsFinanceSettingsRoute
  AuthenticatedAmsStudentsChildIdRoute: typeof AuthenticatedAmsStudentsChildIdRoute
  AuthenticatedAmsStudentsAttendanceRoute: typeof AuthenticatedAmsStudentsAttendanceRoute
  AuthenticatedAmsStudentsDataRoute: typeof AuthenticatedAmsStudentsDataRoute
  AuthenticatedAmsStudentsGuardiansRoute: typeof AuthenticatedAmsStudentsGuardiansRoute
  AuthenticatedAmsStudentsPromotionsRoute: typeof AuthenticatedAmsStudentsPromotionsRoute
  AuthenticatedAmsStudentsRegistryRoute: typeof AuthenticatedAmsStudentsRegistryRoute
  AuthenticatedAmsAcademicsIndexRoute: typeof AuthenticatedAmsAcademicsIndexRoute
  AuthenticatedAmsFinanceIndexRoute: typeof AuthenticatedAmsFinanceIndexRoute
  AuthenticatedAmsStudentsIndexRoute: typeof AuthenticatedAmsStudentsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedChildFileRoute: AuthenticatedChildFileRoute,
  AuthenticatedChildReportsRoute: AuthenticatedChildReportsRoute,
  AuthenticatedClassChatRoute: AuthenticatedClassChatRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedMyApplicationsRoute: AuthenticatedMyApplicationsRoute,
  AuthenticatedPaymentsRoute: AuthenticatedPaymentsRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedReserveRoute: AuthenticatedReserveRoute,
  AuthenticatedStudyPlansRoute: AuthenticatedStudyPlansRoute,
  AuthenticatedAdminAuditRoute: AuthenticatedAdminAuditRoute,
  AuthenticatedAdminInboxRoute: AuthenticatedAdminInboxRoute,
  AuthenticatedAdminPermissionsRoute: AuthenticatedAdminPermissionsRoute,
  AuthenticatedAdminSiteContentRoute: AuthenticatedAdminSiteContentRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedAmsActivityRoute: AuthenticatedAmsActivityRoute,
  AuthenticatedAmsFormBuilderRoute: AuthenticatedAmsFormBuilderRoute,
  AuthenticatedAmsQueueRoute: AuthenticatedAmsQueueRoute,
  AuthenticatedAmsReportsRoute: AuthenticatedAmsReportsRoute,
  AuthenticatedAmsReservationsRoute: AuthenticatedAmsReservationsRoute,
  AuthenticatedAmsSeasonsRoute: AuthenticatedAmsSeasonsRoute,
  AuthenticatedAmsSeatsRoute: AuthenticatedAmsSeatsRoute,
  AuthenticatedAmsWaitingListRoute: AuthenticatedAmsWaitingListRoute,
  AuthenticatedApplyApplicationIdRoute: AuthenticatedApplyApplicationIdRoute,
  AuthenticatedApplyNewRoute: AuthenticatedApplyNewRoute,
  AuthenticatedTrackApplicationIdRoute: AuthenticatedTrackApplicationIdRoute,
  AuthenticatedAmsIndexRoute: AuthenticatedAmsIndexRoute,
  AuthenticatedAdminTeachersTeacherIdRoute:
    AuthenticatedAdminTeachersTeacherIdRoute,
  AuthenticatedAmsAcademicsAssessmentsRoute:
    AuthenticatedAmsAcademicsAssessmentsRoute,
  AuthenticatedAmsAcademicsAssignmentsRoute:
    AuthenticatedAmsAcademicsAssignmentsRoute,
  AuthenticatedAmsAcademicsCalendarRoute:
    AuthenticatedAmsAcademicsCalendarRoute,
  AuthenticatedAmsAcademicsChatRoute: AuthenticatedAmsAcademicsChatRoute,
  AuthenticatedAmsAcademicsCurriculumRoute:
    AuthenticatedAmsAcademicsCurriculumRoute,
  AuthenticatedAmsAcademicsPlansRoute: AuthenticatedAmsAcademicsPlansRoute,
  AuthenticatedAmsAcademicsReportsRoute: AuthenticatedAmsAcademicsReportsRoute,
  AuthenticatedAmsAcademicsSettingsRoute:
    AuthenticatedAmsAcademicsSettingsRoute,
  AuthenticatedAmsApplicationsApplicationIdRoute:
    AuthenticatedAmsApplicationsApplicationIdRoute,
  AuthenticatedAmsFinanceClaimsRoute: AuthenticatedAmsFinanceClaimsRoute,
  AuthenticatedAmsFinanceInvoicesRoute: AuthenticatedAmsFinanceInvoicesRoute,
  AuthenticatedAmsFinanceReportsRoute: AuthenticatedAmsFinanceReportsRoute,
  AuthenticatedAmsFinanceSettingsRoute: AuthenticatedAmsFinanceSettingsRoute,
  AuthenticatedAmsStudentsChildIdRoute: AuthenticatedAmsStudentsChildIdRoute,
  AuthenticatedAmsStudentsAttendanceRoute:
    AuthenticatedAmsStudentsAttendanceRoute,
  AuthenticatedAmsStudentsDataRoute: AuthenticatedAmsStudentsDataRoute,
  AuthenticatedAmsStudentsGuardiansRoute:
    AuthenticatedAmsStudentsGuardiansRoute,
  AuthenticatedAmsStudentsPromotionsRoute:
    AuthenticatedAmsStudentsPromotionsRoute,
  AuthenticatedAmsStudentsRegistryRoute: AuthenticatedAmsStudentsRegistryRoute,
  AuthenticatedAmsAcademicsIndexRoute: AuthenticatedAmsAcademicsIndexRoute,
  AuthenticatedAmsFinanceIndexRoute: AuthenticatedAmsFinanceIndexRoute,
  AuthenticatedAmsStudentsIndexRoute: AuthenticatedAmsStudentsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  GalleryRoute: GalleryRoute,
  KindergartenRoute: KindergartenRoute,
  NewsRoute: NewsRoute,
  PrimaryRoute: PrimaryRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SchoolLifeRoute: SchoolLifeRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StagesRoute: StagesRoute,
  TermsRoute: TermsRoute,
  TestimonialsRoute: TestimonialsRoute,
  InviteTokenRoute: InviteTokenRoute,
  LegalSlugRoute: LegalSlugRoute,
  AdmissionsIndexRoute: AdmissionsIndexRoute,
  TrackIndexRoute: TrackIndexRoute,
  ApiAmsBackupRoute: ApiAmsBackupRoute,
  AdmissionsStageSlugClassroomsRoute: AdmissionsStageSlugClassroomsRoute,
  AdmissionsStageSlugIndexRoute: AdmissionsStageSlugIndexRoute,
  AdmissionsStageSlugClassroomClassroomSlugRoute:
    AdmissionsStageSlugClassroomClassroomSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
